import type { Emitter } from '../builder';

/**
 * A built-in emitter preset is a fully-configured emitter (minus its id)
 * that the seeder writes into the cross-project preset library on first run.
 * Most presets reference a built-in bank texture by name; that creates a
 * dependency the seeder has to satisfy by writing textures before presets.
 *
 * These are starting points, not constraints — once seeded, the user can
 * tweak, rename, duplicate, or delete them like any other preset.
 */
export interface BuiltinPreset {
  /** Filename without extension — `<name>.json` on disk. */
  name: string;
  description: string;
  emitter: Omit<Emitter, 'id'>;
}

export const BUILTIN_PRESETS: BuiltinPreset[] = [
  {
    name: 'foot-dust',
    description: 'Small dust kicked up at feet — drifts up and back, then fades.',
    emitter: {
      name: 'foot-dust',
      layer: 'back',
      startFrame: 0,
      offset: { x: 0, y: 0 },
      config: {
        texture: { kind: 'bank', name: 'dot-soft' },
        tint: [0xb8a890, 0xa89880, 0xc0b098],
        lifespan: { min: 250, max: 450 },
        speed: { min: 12, max: 28 },
        // Phaser angles: 0° right, 90° down. -90° to -135° = up and back.
        angle: { min: -135, max: -90 },
        gravityY: 60,
        scale: { start: 0.8, end: 0.2 },
        alpha: { start: 0.7, end: 0 },
        quantity: 1,
        frequency: 70,
        blendMode: 'NORMAL',
      },
    },
  },
  {
    name: 'jump-puff',
    description: 'Light puff at jump start — radial outward.',
    emitter: {
      name: 'jump-puff',
      layer: 'back',
      startFrame: 0,
      endFrame: 0,
      offset: { x: 0, y: -4 },
      config: {
        texture: { kind: 'bank', name: 'circle-soft' },
        tint: 0xe8e8f0,
        lifespan: { min: 200, max: 350 },
        speed: { min: 30, max: 70 },
        angle: { min: 180, max: 360 }, // outward + down
        gravityY: 40,
        scale: { start: 0.9, end: 0.1 },
        alpha: { start: 0.8, end: 0 },
        quantity: 6,
        frequency: -1, // burst on entry
        blendMode: 'NORMAL',
      },
    },
  },
  {
    name: 'land-impact',
    description: 'Radial dust burst on landing.',
    emitter: {
      name: 'land-impact',
      layer: 'back',
      startFrame: 0,
      endFrame: 0,
      offset: { x: 0, y: -2 },
      config: {
        texture: { kind: 'bank', name: 'dot-soft' },
        tint: [0xa89880, 0xb8a890, 0x988868],
        lifespan: { min: 300, max: 500 },
        speed: { min: 50, max: 110 },
        angle: { min: 200, max: 340 },
        gravityY: 80,
        scale: { start: 1, end: 0.2 },
        alpha: { start: 0.85, end: 0 },
        quantity: 10,
        frequency: -1,
        blendMode: 'NORMAL',
      },
    },
  },
  {
    name: 'dash-trail',
    description: 'Soft afterimage trail behind a dashing character.',
    emitter: {
      name: 'dash-trail',
      layer: 'back',
      startFrame: 0,
      offset: { x: 0, y: -16 },
      config: {
        texture: { kind: 'bank', name: 'glow-soft' },
        tint: 0x6aa9ff,
        lifespan: { min: 250, max: 400 },
        speed: { min: 0, max: 20 },
        angle: { min: 90, max: 90 },
        gravityY: 0,
        scale: { start: 1.2, end: 0.4 },
        alpha: { start: 0.4, end: 0 },
        quantity: 1,
        frequency: 25,
        blendMode: 'ADD',
      },
    },
  },
  {
    name: 'impact-spark',
    description: 'Bright yellow spark burst on a hit frame.',
    emitter: {
      name: 'impact-spark',
      layer: 'front',
      startFrame: 0,
      endFrame: 0,
      offset: { x: 0, y: -16 },
      config: {
        texture: { kind: 'bank', name: 'spark-soft' },
        tint: [0xffe060, 0xffffff, 0xffaa30],
        lifespan: { min: 120, max: 240 },
        speed: { min: 80, max: 180 },
        angle: { min: 0, max: 360 },
        gravityY: 0,
        scale: { start: 1, end: 0 },
        alpha: { start: 1, end: 0 },
        quantity: 12,
        frequency: -1,
        blendMode: 'ADD',
      },
    },
  },
  {
    name: 'charge-glow',
    description: 'Slow rising soft glow during a charge-up — pulses inward.',
    emitter: {
      name: 'charge-glow',
      layer: 'back',
      startFrame: 0,
      offset: { x: 0, y: -16 },
      config: {
        texture: { kind: 'bank', name: 'glow-soft' },
        tint: [0x6aff9e, 0x80ffff, 0x6aa9ff],
        lifespan: { min: 400, max: 700 },
        speed: { min: 5, max: 15 },
        angle: { min: 240, max: 300 },
        gravityY: -20,
        scale: { start: 0.4, end: 1.2 },
        alpha: { start: 0, end: 0.6 },
        quantity: 1,
        frequency: 90,
        blendMode: 'ADD',
      },
    },
  },
  {
    name: 'magic-trail',
    description: 'Sparkly trail of stars rising — good for spell wind-ups.',
    emitter: {
      name: 'magic-trail',
      layer: 'front',
      startFrame: 0,
      offset: { x: 0, y: -8 },
      config: {
        texture: { kind: 'bank', name: 'star-soft' },
        tint: [0xff80ff, 0x80a0ff, 0xffffff, 0xffd0ff],
        lifespan: { min: 350, max: 600 },
        speed: { min: 15, max: 35 },
        angle: { min: 220, max: 320 },
        gravityY: -10,
        scale: { start: 0.7, end: 0 },
        alpha: { start: 1, end: 0 },
        quantity: 1,
        frequency: 50,
        blendMode: 'ADD',
      },
    },
  },
  {
    name: 'explosion',
    description: 'Big radial burst of orange/red glowing particles.',
    emitter: {
      name: 'explosion',
      layer: 'front',
      startFrame: 0,
      endFrame: 0,
      offset: { x: 0, y: -16 },
      config: {
        texture: { kind: 'bank', name: 'circle-soft' },
        tint: [0xffaa30, 0xff6020, 0xffe080, 0xff3010],
        lifespan: { min: 250, max: 500 },
        speed: { min: 80, max: 220 },
        angle: { min: 0, max: 360 },
        gravityY: 30,
        scale: { start: 1.4, end: 0.2 },
        alpha: { start: 1, end: 0 },
        quantity: 24,
        frequency: -1,
        blendMode: 'ADD',
      },
    },
  },
  {
    name: 'smoke-trail',
    description: 'Slow rising smoke — long lifespan, gentle drift.',
    emitter: {
      name: 'smoke-trail',
      layer: 'back',
      startFrame: 0,
      offset: { x: 0, y: -16 },
      config: {
        texture: { kind: 'bank', name: 'glow-soft' },
        tint: [0x303038, 0x404048, 0x282830],
        lifespan: { min: 800, max: 1400 },
        speed: { min: 8, max: 20 },
        angle: { min: 250, max: 290 },
        gravityY: -15,
        scale: { start: 0.6, end: 1.4 },
        alpha: { start: 0.5, end: 0 },
        quantity: 1,
        frequency: 80,
        blendMode: 'NORMAL',
      },
    },
  },
  {
    name: 'fire-burst',
    description: 'Continuous fire emission — orange flames streaming up.',
    emitter: {
      name: 'fire-burst',
      layer: 'back',
      startFrame: 0,
      offset: { x: 0, y: -8 },
      config: {
        texture: { kind: 'bank', name: 'circle-soft' },
        tint: [0xff8020, 0xffc060, 0xffe080, 0xff4010],
        lifespan: { min: 250, max: 500 },
        speed: { min: 30, max: 80 },
        angle: { min: 250, max: 290 },
        gravityY: -40,
        scale: { start: 1, end: 0.1 },
        alpha: { start: 1, end: 0 },
        quantity: 2,
        frequency: 30,
        blendMode: 'ADD',
      },
    },
  },
  {
    name: 'shockwave',
    description: 'Single expanding ring on impact — uses the soft ring texture.',
    emitter: {
      name: 'shockwave',
      layer: 'front',
      startFrame: 0,
      endFrame: 0,
      offset: { x: 0, y: -16 },
      config: {
        texture: { kind: 'bank', name: 'ring-soft' },
        tint: 0xffffff,
        lifespan: 300,
        speed: 0,
        angle: 0,
        gravityY: 0,
        scale: { start: 0.4, end: 3 },
        alpha: { start: 1, end: 0 },
        quantity: 1,
        frequency: -1,
        blendMode: 'ADD',
      },
    },
  },
  {
    name: 'sparkle-rise',
    description: 'Twinkling stars drifting upward — pickup / rare loot vibe.',
    emitter: {
      name: 'sparkle-rise',
      layer: 'front',
      startFrame: 0,
      offset: { x: 0, y: 0 },
      config: {
        texture: { kind: 'bank', name: 'star-small' },
        tint: [0xffd060, 0xffffff, 0x80c0ff, 0xffe0a0],
        lifespan: { min: 600, max: 1000 },
        speed: { min: 15, max: 30 },
        angle: { min: 250, max: 290 },
        gravityY: -20,
        scale: { start: 0.6, end: 0.2 },
        alpha: { start: 1, end: 0 },
        quantity: 1,
        frequency: 100,
        blendMode: 'ADD',
      },
    },
  },

  // ---- Modifier showcase presets ----
  // The three below demonstrate the synthetic motion modifiers (swirl, wave,
  // drag) so you have a working starting point and can see how each one
  // reads. Tweak freely.

  {
    name: 'vortex',
    description: 'Magic-portal swirl — particles orbit the emit point.',
    emitter: {
      name: 'vortex',
      layer: 'front',
      startFrame: 0,
      offset: { x: 0, y: -16 },
      config: {
        texture: { kind: 'bank', name: 'glow-soft' },
        tint: [0xa080ff, 0x80a0ff, 0xc080ff, 0xffffff],
        lifespan: { min: 800, max: 1500 },
        speed: { min: 20, max: 40 },
        angle: { min: 0, max: 360 },
        gravityY: 0,
        scale: { start: 0.6, end: 0.1 },
        alpha: { start: 0.9, end: 0 },
        quantity: 2,
        frequency: 60,
        blendMode: 'ADD',
        swirl: { strength: 350 },
        drag: 0.6,
      },
    },
  },
  {
    name: 'floating-leaves',
    description: 'Falling debris that drifts side-to-side — wave + spin.',
    emitter: {
      name: 'floating-leaves',
      layer: 'front',
      startFrame: 0,
      offset: { x: 0, y: -64 },
      config: {
        texture: { kind: 'bank', name: 'triangle-small' },
        tint: [0xc8a060, 0xa07840, 0xb88848, 0x886030],
        lifespan: { min: 1500, max: 2500 },
        speed: { min: 15, max: 35 },
        angle: { min: 75, max: 105 },
        gravityY: 30,
        scale: { start: 1, end: 0.6 },
        alpha: { start: 1, end: 0 },
        quantity: 1,
        frequency: 250,
        blendMode: 'NORMAL',
        rotateStart: { min: 0, max: 360 },
        rotateRate: 90,
        wave: { amplitude: 18, frequency: 1.2, axis: 'x' },
      },
    },
  },
  {
    name: 'settling-dust',
    description: 'Burst that slows down quickly — drag in action.',
    emitter: {
      name: 'settling-dust',
      layer: 'back',
      startFrame: 0,
      endFrame: 0,
      offset: { x: 0, y: -2 },
      config: {
        texture: { kind: 'bank', name: 'dot-soft' },
        tint: [0xb0a090, 0xc0b0a0, 0xa09080],
        lifespan: { min: 600, max: 1000 },
        speed: { min: 80, max: 160 },
        angle: { min: 200, max: 340 },
        gravityY: 80,
        scale: { start: 1, end: 0.3 },
        alpha: { start: 0.85, end: 0 },
        quantity: 14,
        frequency: -1,
        blendMode: 'NORMAL',
        drag: 1.8,
      },
    },
  },
];
